{{- if .Values.gatewayApi.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ include "service.namespace" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    service.tier: {{TIER}}
    service.workload: {{TIER}}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "service.hostnames" . }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayApi.gatewayName }}
  hostnames:
  {{- range .Values.dns.domains }}
    - {{ . }}.{{ $.Values.global.domain }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "service.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}