{{- if and .Values.ingress.enabled (ne .Values.global.domain "localhost") -}}
{{- $serviceName := include "service.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $envDomain := .Values.global.domain -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ include "service.namespace" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    service.tier: {{TIER}}
    service.workload: {{TIER}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  tls:
  - secretName: {{ $serviceName }}-tls
    hosts:
    {{- range .Values.dns.domains }}
      - {{ . }}.{{ $envDomain }}
    {{- end }}
  rules:
  {{- range .Values.dns.domains }}
  - host: {{ . }}.{{ $envDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $servicePort }}
  {{- end }}
{{- end }}
